name: GemsUltimate
main: aoidev.crystal.Main
version: 1.0.0
api-version: 1.20
author: AoiDev
softdepend: [Vault, PlaceholderAPI]

commands:
  gems:
    description: Main command
    permission: gems.admin

permissions:
  gems.admin:
    default: op
